phpfpm:
  image: "registry.cn-hangzhou.aliyuncs.com/phpfpm/phpfpm-front:1.5-credit"
  volumes:
   - ./:/var/www/html/
  cap_add:
   - SYS_PTRACE
  environment:
   - APP_ENV=dev
  container_name: credit-sdk-phpfpm