<?php

//通用错误规范
define('SLIDING_VERIFICATION_INCORRECT', 100);
define('FILE_NOT_EXIST', 101);
define('FILE_EXTENSION_NOT_SUPPORTED', 102);
define('FILE_SIZE_LIMIT_EXCEEDED', 103);
define('FILE_UPLOAD_INCORRECT', 104);
define('FILE_UPLOAD_PATH_NOT_EXIST', 105);
define('CSRF_VERIFICATION_FAILURE', 106);
define('PARAMETER_FORMAT_ERROR', 108);
define('PARAMETER_INCORRECT', 109);
define('PARAMETER_NOT_EMPTY', 110);
define('RESOURCE_CAN_NOT_MODIFY', 111);
define('RESOURCE_EXISTS', 112);
define('RESOURCE_NOT_EXISTS', 113);
define('USER_NOT_LOGIN', 114);
define('USER_STATUS_DISABLED', 115);
define('USER_PURVIEW_UNASSIGNED', 116);
define('USER_IDENTITY_AUTHENTICATION_FAILED', 117);

//通用字段错误规范
define('TITLE_FORMAT_INCORRECT', 201);
define('NAME_FORMAT_INCORRECT', 202);
define('SUBJECT_NAME_FORMAT_INCORRECT', 203);
define('UNIFIED_IDENTIFIER_FORMAT_INCORRECT', 204);
define('ID_CARD_FORMAT_INCORRECT', 205);
define('CELLPHONE_FORMAT_INCORRECT', 206);
define('TELEPHONE_FORMAT_INCORRECT', 207);
define('PASSWORD_FORMAT_INCORRECT', 208);
define('CONFIRM_PASSWORD_IDENTICAL_DENIED', 209);
define('REASON_FORMAT_INCORRECT', 210);
define('DESCRIPTION_FORMAT_INCORRECT', 211);
define('CONTENT_FORMAT_INCORRECT', 212);
define('REMARK_FORMAT_INCORRECT', 213);
define('ATTACHMENT_FORMAT_INCORRECT', 214);
define('PICTURE_FORMAT_INCORRECT', 215);
define('STAFF_FORMAT_INCORRECT', 216);
define('ACCOUNT_NOT_EXISTS', 217);
define('PASSWORD_INCORRECT', 218);
define('STAFF_NOT_EXISTS', 219);
define('ACCOUNT_PASSWORD_INCORRECT', 220);
define('OLD_PASSWORD_INCORRECT', 221);
define('STATUS_FORMAT_INCORRECT', 222);
define('EMAIL_FORMAT_INCORRECT', 223);
define('REAL_NAME_FORMAT_INCORRECT', 224);
define('MEMBER_FORMAT_INCORRECT', 225);
define('MEMBER_NOT_EXISTS', 226);
define('RESOURCE_DATA_NOT_EXISTS', 227);
define('ENTERPRISE_NOT_EXISTS', 228);
define('RESOURCE_DATA_FORMAT_INCORRECT', 229);
define('ENTERPRISE_FORMAT_INCORRECT', 230);
define('ORGANIZATION_FORMAT_INCORRECT', 231);
define('ORGANIZATION_NOT_EXISTS', 232);
define('USER_ACCOUNT_LOCKED', 233);

//委办局管理错误规范
define('ORGANIZATION_SHORT_NAME_FORMAT_INCORRECT', 1001);
define('ORGANIZATION_JURISDICTION_AREA_FORMAT_INCORRECT', 1002);
define('ORGANIZATION_NAME_EXISTS', 1003);
define('ORGANIZATION_SHORT_NAME_EXISTS', 1004);
define('ORGANIZATION_JURISDICTION_AREA_NOT_EXISTS', 1005);
define('ORGANIZATION_UNIFIED_IDENTIFIER_EXISTS', 1006);

//科室管理错误规范
define('DEPARTMENT_ORGANIZATION_FORMAT_INCORRECT', 1101);
define('DEPARTMENT_NAME_EXISTS', 1102);
define('DEPARTMENT_ORGANIZATION_NOT_EXISTS', 1103);

//角色管理错误规范
define('ROLE_PURVIEW_FORMAT_INCORRECT', 1201);
define('ROLE_NAME_EXISTS', 1202);

//员工管理错误规范
define('STAFF_CATEGORY_FORMAT_INCORRECT', 1301);
define('STAFF_ROLES_FORMAT_INCORRECT', 1302);
define('STAFF_ORGANIZATION_FORMAT_INCORRECT', 1303);
define('STAFF_DEPARTMENT_FORMAT_INCORRECT', 1304);
define('STAFF_CELLPHONE_EXISTS', 1305);
define('STAFF_ORGANIZATION_NOT_EXISTS', 1306);
define('STAFF_DEPARTMENT_NOT_EXISTS', 1307);
define('STAFF_ROLES_NOT_EXISTS', 1308);
define('STAFF_NAVIGATION_FORMAT_INCORRECT', 1309);

//字典项管理错误规范
define('DICTIONARY_CATEGORY_FORMAT_INCORRECT', 1401);
define('DICTIONARY_ITEM_NAME_EXISTS', 1402);
define('DICTIONARY_CATEGORY_NOT_EXISTS', 1403);

//新闻分类管理错误规范
define('ARTICLE_CATEGORY_LEVEL_FORMAT_INCORRECT', 1501);
define('ARTICLE_CATEGORY_PARENT_CATEGORY_FORMAT_INCORRECT', 1502);
define('ARTICLE_CATEGORY_NAME_EXISTS', 1503);
define('ARTICLE_CATEGORY_PARENT_CATEGORY_NOT_EXISTS', 1504);
define('ARTICLE_CATEGORY_STYLE_FORMAT_INCORRECT', 1505);
define('ARTICLE_CATEGORY_DIY_CONTENT_FORMAT_INCORRECT', 1506);

//新闻管理错误规范
define('ARTICLE_SOURCE_FORMAT_INCORRECT', 1601);
define('ARTICLE_CATEGORY_FORMAT_INCORRECT', 1602);
define('ARTICLE_PUB_DATE_FORMAT_INCORRECT', 1603);
define('ARTICLE_ATTACHMENTS_FORMAT_INCORRECT', 1604);
define('ARTICLE_ATTACHMENTS_COUNT_INCORRECT', 1605);
define('ARTICLE_IS_SLIDES_FORMAT_INCORRECT', 1606);
define('ARTICLE_IS_HOME_SLIDES_FORMAT_INCORRECT', 1607);
define('ARTICLE_CATEGORY_NOT_EXISTS', 1608);
define('ARTICLE_CONTENT_COUNT_INCORRECT', 1609);

//前台用户管理错误规范
define('MEMBER_GENDER_FORMAT_INCORRECT', 1701);
define('MEMBER_EMAIL_FORMAT_INCORRECT', 1702);
define('MEMBER_ADDRESS_FORMAT_INCORRECT', 1703);
define('MEMBER_QUESTION_FORMAT_INCORRECT', 1704);
define('MEMBER_ANSWER_FORMAT_INCORRECT', 1705);
define('MEMBER_CELLPHONE_EXISTS', 1706);
define('MEMBER_ID_CARD_EXISTS', 1707);
define('MEMBER_ANSWER_INCORRECT', 1708);

//目录管理错误规范
define('DIRECTORY_NAME_FORMAT_INCORRECT', 1801);
define('DIRECTORY_IDENTIFY_FORMAT_INCORRECT', 1802);
define('DIRECTORY_SUBJECT_CATEGORY_FORMAT_INCORRECT', 1803);
define('DIRECTORY_INFO_CATEGORY_FORMAT_INCORRECT', 1804);
define('DIRECTORY_SOURCE_UNITS_FORMAT_INCORRECT', 1805);
define('DIRECTORY_ITEMS_FORMAT_INCORRECT', 1806);
define('DIRECTORY_NAME_EXISTS', 1807);
define('DIRECTORY_IDENTIFY_EXISTS', 1808);
define('DIRECTORY_ITEMS_NAME_FORMAT_INCORRECT', 1809);
define('DIRECTORY_ITEMS_IDENTIFY_FORMAT_INCORRECT', 1810);
define('DIRECTORY_ITEMS_NAME_EXISTS', 1811);
define('DIRECTORY_ITEMS_IDENTIFY_EXISTS', 1812);
define('DIRECTORY_ITEMS_DATA_TYPE_FORMAT_INCORRECT', 1813);
define('DIRECTORY_ITEMS_DATA_LENGTH_FORMAT_INCORRECT', 1814);
define('DIRECTORY_ITEMS_OPTIONAL_RANGE_FORMAT_INCORRECT', 1815);
define('DIRECTORY_ITEMS_REQUIRED_FORMAT_INCORRECT', 1816);
define('DIRECTORY_ITEMS_DESENSITIZATION_FORMAT_INCORRECT', 1817);
define('DIRECTORY_ITEMS_DESENSITIZATION_RULE_FORMAT_INCORRECT', 1818);
define('DIRECTORY_ITEMS_PUBLICATION_RANGE_FORMAT_INCORRECT', 1819);
define('DIRECTORY_ITEMS_COUNT_INCORRECT', 1820);
define('DIRECTORY_ITEMS_REMARKS_FORMAT_INCORRECT', 1821);
define('DIRECTORY_ITEMS_SUBJECT_NAME_IDENTIFY_FORMAT_INCORRECT', 1822);
define('DIRECTORY_SOURCE_UNITS_NOT_EXISTS', 1823);
define('DIRECTORY_SNAPSHOT_FORMAT_INCORRECT', 1824);
define('DIRECTORY_SNAPSHOT_NOT_EXISTS', 1825);
define('DIRECTORY_EXISTS', 1826);

//网站自定义管理错误规范
define('HELP_PAGE_CONFIG_STYLE_FORMAT_INCORRECT', 1901);
define('HELP_PAGE_CONFIG_DIY_CONTENT_FORMAT_INCORRECT', 1902);
define('HELP_PAGE_CONFIG_TITLE_EXISTS', 1903);
define('HOME_PAGE_CONFIG_DIY_CONTENT_FORMAT_INCORRECT', 1904);

//信用数据管理错误规范
define('DATA_IDENTIFY_FORMAT_INCORRECT', 2101);
define('DATA_SUBJECT_CATEGORY_FORMAT_INCORRECT', 2102);
define('DATA_INFO_CATEGORY_FORMAT_INCORRECT', 2103);
define('DATA_PUBLICATION_RANGE_FORMAT_INCORRECT', 2104);
define('DATA_EXPIRE_DATE_FORMAT_INCORRECT', 2105);
define('DATA_ITEMS_FORMAT_INCORRECT', 2106);
define('DATA_DIRECTORY_FORMAT_INCORRECT', 2107);
define('DATA_DIRECTORY_NOT_EXISTS', 2108);
define('DATA_DIRECTORY_SNAPSHOT_NOT_EXISTS', 2109);
define('DATA_EXISTS', 2110);
define('DATA_ITEMS_COUNT_FORMAT_INCORRECT', 2111);

//信用数据上传任务管理错误规范
define('UPLOAD_DATA_TASK_NAME_FORMAT_INCORRECT', 2201);
define('UPLOAD_DATA_TASK_NAME_EXISTS', 2202);
define('UPLOAD_DATA_TASK_NAME_NOT_EXISTS', 2203);
define('UPLOAD_DATA_TASK_DIRECTORY_FORMAT_INCORRECT', 2204);
define('UPLOAD_DATA_TASK_DIRECTORY_NOT_EXISTS', 2205);
define('STAFF_NOT_BELONG_TO_DIRECTORY_SOURCE_UNITS', 2206);
define('UPLOAD_FILE_EXCEED_MAX_LINES_LIMIT', 2207);

//信用数据导出任务管理错误规范
define('EXPORT_DATA_TASK_SIZE_FORMAT_INCORRECT', 2301);
define('EXPORT_DATA_TASK_OFFSET_FORMAT_INCORRECT', 2302);
define('EXPORT_DATA_TASK_NAME_NOT_EXISTS', 2303);
define('EXPORT_DATA_TASK_DIRECTORY_SNAPSHOT_FORMAT_INCORRECT', 2304);
define('EXPORT_DATA_TASK_DIRECTORY_SNAPSHOT_NOT_EXISTS', 2305);
define('EXPORT_DATA_SIZE_EXCEED_MAX_LINES_LIMIT', 2306);

//信用承诺管理错误规范
define('COMMITMENT_CODE_FORMAT_INCORRECT', 2401);
define('COMMITMENT_SUBJECT_NAME_FORMAT_INCORRECT', 2402);
define('COMMITMENT_SUBJECT_CATEGORY_FORMAT_INCORRECT', 2403);
define('COMMITMENT_IDENTIFY_FORMAT_INCORRECT', 2404);
define('COMMITMENT_TYPE_ID_FORMAT_INCORRECT', 2405);
define('COMMITMENT_TYPE_OTHER_FORMAT_INCORRECT', 2406);
define('COMMITMENT_REASON_FORMAT_INCORRECT', 2407);
define('COMMITMENT_CONTENT_FORMAT_INCORRECT', 2408);
define('COMMITMENT_LIABILITY_BREACH_COMMITMENT_FORMAT_INCORRECT', 2409);
define('COMMITMENT_DATE_FORMAT_INCORRECT', 2410);
define('COMMITMENT_ACCEPTANCE_UNIT_FORMAT_INCORRECT', 2411);
define('COMMITMENT_ACCEPTANCE_UNIT_IDENTIFY_FORMAT_INCORRECT', 2412);
define('COMMITMENT_PUBLICATION_TYPE_FORMAT_INCORRECT', 2413);
define('COMMITMENT_REMARKS_FORMAT_INCORRECT', 2414);
define('COMMITMENT_FULFILLMENT_STATUS_FORMAT_INCORRECT', 2415);
define('COMMITMENT_UNPERFORMED_COMMITMENT_CONTENT_FORMAT_INCORRECT', 2416);
define('COMMITMENT_LIABILITY_BREACH_COMMITMENT_CONTENT_FORMAT_INCORRECT', 2417);
define('COMMITMENT_FULFILLMENT_STATUS_DATE_FORMAT_INCORRECT', 2418);
define('COMMITMENT_ACCEPTANCE_CONFIRM_UNIT_FORMAT_INCORRECT', 2419);
define('COMMITMENT_ACCEPTANCE_CONFIRM_UNIT_IDENTIFY_FORMAT_INCORRECT', 2420);
define('COMMITMENT_SUPERVISE_STATUS_FORMAT_INCORRECT', 2421);
define('COMMITMENT_NOT_EXISTS', 2422);
define('COMMITMENT_EXISTS', 2423);
define('COMMITMENT_VALIDITY_FORMAT_INCORRECT', 2424);
define('PROMISE_EXISTS', 2425);

//应用数据导出任务管理错误规范
define('APPLICATION_EXPORT_DATA_TASK_CATEGORY_FORMAT_INCORRECT', 2501);

//应用数据导入任务管理错误规范
define('APPLICATION_UPLOAD_DATA_TASK_CATEGORY_FORMAT_INCORRECT', 2601);


//合同履约管理错误规范
define('CONTRACT_PERFORMANCE_HTBH_FORMAT_INCORRECT', 2701);
define('CONTRACT_PERFORMANCE_HTMC_FORMAT_INCORRECT', 2702);
define('CONTRACT_PERFORMANCE_HTLX_FORMAT_INCORRECT', 2703);
define('CONTRACT_PERFORMANCE_XMBH_FORMAT_INCORRECT', 2704);
define('CONTRACT_PERFORMANCE_CGR_FORMAT_INCORRECT', 2705);
define('CONTRACT_PERFORMANCE_JFZTTYSHXYDM_FORMAT_INCORRECT', 2706);
define('CONTRACT_PERFORMANCE_CGRDZ_FORMAT_INCORRECT', 2707);
define('CONTRACT_PERFORMANCE_GYS_FORMAT_INCORRECT', 2708);
define('CONTRACT_PERFORMANCE_YFTYSHXYDM_FORMAT_INCORRECT', 2709);
define('CONTRACT_PERFORMANCE_GYSDZ_FORMAT_INCORRECT', 2710);
define('CONTRACT_PERFORMANCE_GYSLXFS_FORMAT_INCORRECT', 2711);
define('CONTRACT_PERFORMANCE_ZYBDMC_FORMAT_INCORRECT', 2712);
define('CONTRACT_PERFORMANCE_GGXH_FORMAT_INCORRECT', 2713);
define('CONTRACT_PERFORMANCE_ZYBDSL_FORMAT_INCORRECT', 2714);
define('CONTRACT_PERFORMANCE_ZYBDDJ_FORMAT_INCORRECT', 2715);
define('CONTRACT_PERFORMANCE_HTJE_FORMAT_INCORRECT', 2716);
define('CONTRACT_PERFORMANCE_LYQX_FORMAT_INCORRECT', 2717);
define('CONTRACT_PERFORMANCE_QZDD_FORMAT_INCORRECT', 2718);
define('CONTRACT_PERFORMANCE_CGFS_FORMAT_INCORRECT', 2719);
define('CONTRACT_PERFORMANCE_HTQDRQ_FORMAT_INCORRECT', 2720);
define('CONTRACT_PERFORMANCE_HTGGRQ_FORMAT_INCORRECT', 2721);
define('CONTRACT_PERFORMANCE_QTBCSY_FORMAT_INCORRECT', 2722);
define('CONTRACT_PERFORMANCE_LYZT_FORMAT_INCORRECT', 2723);
define('CONTRACT_PERFORMANCE_SSQY_FORMAT_INCORRECT', 2724);
define('CONTRACT_PERFORMANCE_SSHY_FORMAT_INCORRECT', 2725);
define('CONTRACT_PERFORMANCE_NOT_EXISTS', 2726);
define('CONTRACT_PERFORMANCE_EXISTS', 2727);
define('CONTRACT_FULFILLMENT_INFO_HTZXJD_FORMAT_INCORRECT', 2728);
define('CONTRACT_FULFILLMENT_INFO_HTZJSFQEZF_FORMAT_INCORRECT', 2729);
define('CONTRACT_SJLYDW_FORMAT_INCORRECT', 2730);
define('CONTRACT_BREACH_INFO_WYF_FORMAT_INCORRECT', 2731);
define('CONTRACT_BREACH_INFO_WYSY_FORMAT_INCORRECT', 2732);
define('CONTRACT_BREACH_INFO_WYYJ_FORMAT_INCORRECT', 2733);
define('CONTRACT_BREACH_INFO_WYZT_FORMAT_INCORRECT', 2734);
define('FULFILLMENT_INFO_EXISTS', 2735);
define('BREACH_INFO_EXISTS', 2736);

//互动交流管理错误规范
define('INTERACTION_CELLPHONE_FORMAT_INCORRECT', 2801);
define('INTERACTION_CONTENT_FORMAT_INCORRECT', 2802);
define('INTERACTION_REPLY_CONTENT_FORMAT_INCORRECT', 2803);
define('INTERACTION_EVIDENCES_FORMAT_INCORRECT', 2804);
define('INTERACTION_EVIDENCES_EXCEED_MAX_LIMIT', 2805);
define('INTERACTION_QUESTION_FORMAT_INCORRECT', 2806);

//信用报告自定义管理错误规范
define('CREDIT_REPORT_COMMON_CONFIG_DIY_CONTENT_FORMAT_INCORRECT', 2901);

//信用报告下载记录管理错误规范
define('CREDIT_REPORT_DOWNLOAD_RECORD_DOMAIN_FORMAT_INCORRECT', 3001);
define('CREDIT_REPORT_DOWNLOAD_RECORD_TARGET_FORMAT_INCORRECT', 3002);
define('CREDIT_REPORT_DOWNLOAD_RECORD_DESCRIPTION_FORMAT_INCORRECT', 3003);
define('CREDIT_REPORT_DOWNLOAD_RECORD_SUBJECT_FORMAT_INCORRECT', 3004);
define('CREDIT_REPORT_SUBJECT_NOT_EXISTS', 3005);
define('CREDIT_REPORT_SUBJECT_CATEGORY_FORMAT_INCORRECT', 3006);

//奖惩备忘录管理错误规范
define('RAP_MEMORANDUM_NAME_FORMAT_INCORRECT', 3101);
define('RAP_MEMORANDUM_DOCUMENT_NO_FORMAT_INCORRECT', 3102);
define('RAP_MEMORANDUM_ORIGINATING_UNIT_FORMAT_INCORRECT', 3103);
define('RAP_MEMORANDUM_RELEASE_DATE_FORMAT_INCORRECT', 3104);
define('RAP_MEMORANDUM_REWARD_TYPE_FORMAT_INCORRECT', 3105);
define('RAP_MEMORANDUM_JOINT_SIGNING_DEPARTMENT_FORMAT_INCORRECT', 3106);
define('RAP_MEMORANDUM_CONTENT_FORMAT_INCORRECT', 3107);
define('RAP_MEMORANDUM_ATTACHMENTS_FORMAT_INCORRECT', 3108);
define('RAP_MEMORANDUM_ATTACHMENTS_COUNT_INCORRECT', 3109);

//奖惩措施管理错误规范
define('RAP_MEASURE_NAME_FORMAT_INCORRECT', 3201);
define('RAP_MEASURE_DESCRIPTION_FORMAT_INCORRECT', 3202);
define('RAP_MEASURE_IMPLEMENTATION_UNITS_FORMAT_INCORRECT', 3203);
define('RAP_MEASURE_IMPLEMENTATION_UNITS_NOT_EXISTS', 3204);
define('RAP_MEASURE_MEMORANDUM_FORMAT_INCORRECT', 3205);
define('RAP_MEASURE_MEMORANDUM_NOT_EXISTS', 3206);

//奖惩案例管理错误规范
define('RAP_CASE_ZJLX_FORMAT_INCORRECT', 3301);
define('RAP_CASE_MEASURE_FORMAT_INCORRECT', 3302);
define('RAP_CASE_DATA_FORMAT_INCORRECT', 3303);
define('RAP_CASE_SJJE_FORMAT_INCORRECT', 3304);
define('RAP_CASE_JCSM_FORMAT_INCORRECT', 3305);
define('RAP_CASE_MEASURE_NOT_EXISTS', 3306);
define('RAP_CASE_DATA_NOT_EXISTS', 3307);
define('RAP_CASE_FEEDBACK_ORGANIZATION_NOT_EXISTS', 3308);
define('RAP_CASE_FEEDBACK_ORGANIZATION_FORMAT_INCORRECT', 3309);

//实名认证-个人认证管理错误规范
define('NATURAL_PERSON_CERTIFICATE_EXISTS', 3401);
define('NATURAL_PERSON_CERTIFICATE_FRONT_ID_CARD_PIC_FORMAT_INCORRECT', 3402);
define('NATURAL_PERSON_CERTIFICATE_BACK_ID_CARD_PIC_FORMAT_INCORRECT', 3403);
define('NATURAL_PERSON_CERTIFICATE_HANDHELD_ID_CARD_PIC_FORMAT_INCORRECT', 3404);
define('NATURAL_PERSON_CERTIFICATE_NOT_EXISTS', 3405);

//实名认证-企业认证管理错误规范
define('ENTERPRISE_CERTIFICATE_ZTMC_FORMAT_INCORRECT', 3501);
define('ENTERPRISE_CERTIFICATE_ZTLB_FORMAT_INCORRECT', 3502);
define('ENTERPRISE_CERTIFICATE_TYSHXYDM_FORMAT_INCORRECT', 3503);
define('ENTERPRISE_CERTIFICATE_FDDBR_FORMAT_INCORRECT', 3504);
define('ENTERPRISE_CERTIFICATE_FDDBRZJLX_FORMAT_INCORRECT', 3505);
define('ENTERPRISE_CERTIFICATE_FDDBRZJHM_FORMAT_INCORRECT', 3506);
define('ENTERPRISE_CERTIFICATE_CLRQ_FORMAT_INCORRECT', 3507);
define('ENTERPRISE_CERTIFICATE_YXQ_FORMAT_INCORRECT', 3508);
define('ENTERPRISE_CERTIFICATE_DZ_FORMAT_INCORRECT', 3509);
define('ENTERPRISE_CERTIFICATE_DJJG_FORMAT_INCORRECT', 3510);
define('ENTERPRISE_CERTIFICATE_GB_FORMAT_INCORRECT', 3511);
define('ENTERPRISE_CERTIFICATE_ZCZB_FORMAT_INCORRECT', 3512);
define('ENTERPRISE_CERTIFICATE_ZCZBBZ_FORMAT_INCORRECT', 3513);
define('ENTERPRISE_CERTIFICATE_HYDM_FORMAT_INCORRECT', 3514);
define('ENTERPRISE_CERTIFICATE_LX_FORMAT_INCORRECT', 3515);
define('ENTERPRISE_CERTIFICATE_JYFW_FORMAT_INCORRECT', 3516);
define('ENTERPRISE_CERTIFICATE_JYZT_FORMAT_INCORRECT', 3517);
define('ENTERPRISE_CERTIFICATE_JYFWMS_FORMAT_INCORRECT', 3518);
define('ENTERPRISE_CERTIFICATE_BUSINESS_LICENSE_PICTURE_FORMAT_INCORRECT', 3519);
define('ENTERPRISE_CERTIFICATE_EXISTS', 3520);

//自主申报管理错误规范
define('SELF_DECLARATION_ATTACHMENTS_FORMAT_INCORRECT', 3601);
define('SELF_DECLARATION_CERTIFICATE_TYPE_FORMAT_INCORRECT', 3602);
define('SELF_DECLARATION_CERTIFICATE_ID_FORMAT_INCORRECT', 3603);
define('SELF_DECLARATION_CERTIFICATE_NOT_EXISTS', 3604);
define('SELF_DECLARATION_ATTACHMENTS_COUNT_FORMAT_INCORRECT', 3605);
define('SELF_DECLARATION_CERTIFICATE_FORMAT_INCORRECT', 3606);

//行业组织评价信息错误规范
define('CM_INDUSTRYORGEVA_SUBJECT_NAME_FORMAT_INCORRECT', 3801);
define('CM_INDUSTRYORGEVA_UNIFIED_IDENTIFIER_FORMAT_INCORRECT', 3802);
define('CM_INDUSTRYORGEVA_INDUSTRY_NAME_FORMAT_INCORRECT', 3803);
define('CM_INDUSTRYORGEVA_EVALUATION_TYPE_FORMAT_INCORRECT', 3804);
define('CM_INDUSTRYORGEVA_EVALUATION_CONTENT_FORMAT_INCORRECT', 3805);

//证书信息错误规范
define('CM_CERTIFICATION_SUBJECT_NAME_FORMAT_INCORRECT', 3901);
define('CM_CERTIFICATION_UNIFIED_IDENTIFIER_FORMAT_INCORRECT', 3902);
define('CM_CERTIFICATION_NAME_FORMAT_INCORRECT', 3903);
define('CM_CERTIFICATION_PUB_DATE_FORMAT_INCORRECT', 3904);
define('CM_CERTIFICATION_VALIDATE_DATE_FORMAT_INCORRECT', 3905);

//动产抵押信息错误规范
define('CM_COLLATERAL_SUBJECT_NAME_FORMAT_INCORRECT', 4001);
define('CM_COLLATERAL_UNIFIED_IDENTIFIER_FORMAT_INCORRECT', 4002);
define('CM_COLLATERAL_REGISTRATION_NUMBER_FORMAT_INCORRECT', 4003);
define('CM_COLLATERAL_REGISTRATION_DATE_FORMAT_INCORRECT', 4004);
define('CM_COLLATERAL_REGISTRATION_AGENCY_FORMAT_INCORRECT', 4005);
define('CM_COLLATERAL_SECURED_BOND_AMOUNT_FORMAT_INCORRECT', 4006);
define('CM_COLLATERAL_MORTGAGE_STATUS_FORMAT_INCORRECT', 4007);

//著作权信息错误规范
define('CM_COPYRIGHT_SUBJECT_NAME_FORMAT_INCORRECT', 4101);
define('CM_COPYRIGHT_UNIFIED_IDENTIFIER_FORMAT_INCORRECT', 4102);
define('CM_COPYRIGHT_TITLE_FORMAT_INCORRECT', 4103);
define('CM_COPYRIGHT_REGISTRATION_NUMBER_FORMAT_INCORRECT', 4104);
define('CM_COPYRIGHT_CONDITIONS_FORMAT_INCORRECT', 4105);
define('CM_COPYRIGHT_REGISTRATION_DATE_FORMAT_INCORRECT', 4106);

//融资信息错误规范
define('CM_FINANCING_SUBJECT_NAME_FORMAT_INCORRECT', 4201);
define('CM_FINANCING_UNIFIED_IDENTIFIER_FORMAT_INCORRECT', 4202);
define('CM_FINANCING_FINANCED_AT_FORMAT_INCORRECT', 4203);
define('CM_FINANCING_STAGE_FORMAT_INCORRECT', 4204);
define('CM_FINANCING_AMOUNT_FORMAT_INCORRECT', 4205);

//软著信息错误规范
define('CM_SOFTWARERIGHT_SUBJECT_NAME_FORMAT_INCORRECT', 4301);
define('CM_SOFTWARERIGHT_UNIFIED_IDENTIFIER_FORMAT_INCORRECT', 4302);
define('CM_SOFTWARERIGHT_TITLE_FORMAT_INCORRECT', 4303);
define('CM_SOFTWARERIGHT_VERSION_FORMAT_INCORRECT', 4304);
define('CM_SOFTWARERIGHT_CATEGORY_FORMAT_INCORRECT', 4305);
define('CM_SOFTWARERIGHT_REGISTRATION_NUMBER_FORMAT_INCORRECT', 4306);
define('CM_SOFTWARERIGHT_REGISTRATION_APPROVAL_DATE_FORMAT_INCORRECT', 4307);

//税务信息错误规范
define('CM_TAXATION_SUBJECT_NAME_FORMAT_INCORRECT', 4401);
define('CM_TAXATION_UNIFIED_IDENTIFIER_FORMAT_INCORRECT', 4402);
define('CM_TAXATION_IDENTIFICATION_NUMBER_FORMAT_INCORRECT', 4403);
define('CM_TAXATION_OUTSTANDING_TAX_BALANCE_FORMAT_INCORRECT', 4404);
define('CM_TAXATION_TOTAL_TAX_AMOUNT_FORMAT_INCORRECT', 4405);

//信用评价指标管理错误规范
define('EVALUATION_INDICATOR_NAME_FORMAT_INCORRECT', 4501);
define('EVALUATION_INDICATOR_CATEGORY_FORMAT_INCORRECT', 4502);
define('EVALUATION_INDICATOR_INFO_CATEGORY_FORMAT_INCORRECT', 4503);
define('EVALUATION_INDICATOR_DESCRIPTION_FORMAT_INCORRECT', 4504);
define('EVALUATION_INDICATOR_SOURCE_FORMAT_INCORRECT', 4505);
define('EVALUATION_INDICATOR_SOURCE_NOT_EXISTS', 4506);
define('EVALUATION_INDICATOR_SOURCE_INFO_CATEGORY_MISMATCH', 4507);

//信用评价模型管理错误规范
define('EVALUATION_SCORE_MODEL_NAME_FORMAT_INCORRECT', 4601);
define('EVALUATION_SCORE_MODEL_OBJECT_FORMAT_INCORRECT', 4602);
define('EVALUATION_SCORE_MODEL_DESCRIPTION_FORMAT_INCORRECT', 4603);
define('EVALUATION_SCORE_MODEL_MAX_SCORE_FORMAT_INCORRECT', 4604);
define('EVALUATION_SCORE_MODEL_BASE_SCORE_FORMAT_INCORRECT', 4605);
define('EVALUATION_SCORE_MODEL_RANKS_FORMAT_INCORRECT', 4606);
define('EVALUATION_SCORE_MODEL_INDICATOR_WEIGHTS_FORMAT_INCORRECT', 4607);
define('EVALUATION_SCORE_MODEL_RANKS_NOT_EXISTS', 4608);
define('EVALUATION_SCORE_MODEL_INDICATOR_WEIGHTS_NOT_EXISTS', 4609);
define('EVALUATION_SCORE_MODEL_RANKS_MAX_SCORE_BELOW_BASE_SCORE', 4610);
define('EVALUATION_SCORE_MODEL_RANKS_RATING_FORMAT_INCORRECT', 4611);
define('EVALUATION_SCORE_MODEL_RANKS_REMINDER_FORMAT_INCORRECT', 4612);
define('EVALUATION_SCORE_MODEL_RANKS_LEVEL_DESCRIPTION_FORMAT_INCORRECT', 4613);
define('EVALUATION_SCORE_MODEL_RANKS_MIN_SCORE_FORMAT_INCORRECT', 4614);
define('EVALUATION_SCORE_MODEL_RANKS_MAX_SCORE_FORMAT_INCORRECT', 4615);
define('EVALUATION_SCORE_MODEL_RANKS_MIN_SCORE_BELOW_MIN_SCORE', 4616);
define('EVALUATION_SCORE_MODEL_RANKS_MAX_SCORE_HIGHER_THAN_MAX_SCORE', 4617);
define('EVALUATION_SCORE_MODEL_RANKS_MIN_SCORE_INCORRECT', 4618);
define('EVALUATION_SCORE_MODEL_RANKS_MAX_SCORE_INCORRECT', 4619);
define('EVALUATION_SCORE_MODEL_RANKS_MIN_SCORE_HIGHER_THAN_RANKS_MAX_SCORE', 4620);
define('EVALUATION_SCORE_MODEL_RANKS_SCORE_INCOHERENCE', 4621);
define('EVALUATION_SCORE_MODEL_RANKS_SCORE_OVERLAP', 4622);
define('EVALUATION_SCORE_MODEL_INDICATOR_WEIGHTS_PERCENTAGE_FORMAT_INCORRECT', 4623);
define('EVALUATION_SCORE_MODEL_INDICATOR_WEIGHTS_SCORE_FORMAT_INCORRECT', 4624);
define('EVALUATION_SCORE_MODEL_INDICATOR_WEIGHTS_INDICATOR_ID_FORMAT_INCORRECT', 4625);
define('EVALUATION_SCORE_MODEL_INDICATOR_WEIGHTS_PERCENTAGE_SUM_NOT_EQUAL_EXPECTED', 4626);
define('EVALUATION_SCORE_MODEL_RANKS_RATING_EXISTS', 4627);
define('EVALUATION_SCORE_MODEL_RANKS_COUNT_FORMAT_INCORRECT', 4628);
define('EVALUATION_SCORE_MODEL_OBJECT_INDICATOR_SOURCE_SUBJECT_CATEGORY_MISMATCHING', 4629);
define('EVALUATION_SCORE_MODEL_INDICATOR_WEIGHTS_INDICATOR_EXISTS', 4630);

//信用评价场景管理错误规范
define('EVALUATION_SCENARIO_NAME_FORMAT_INCORRECT', 4801);
define('EVALUATION_SCENARIO_DESCRIPTION_FORMAT_INCORRECT', 4802);
define('EVALUATION_SCENARIO_SCORE_MODEL_FORMAT_INCORRECT', 4803);
define('EVALUATION_SCENARIO_SCORE_MODEL_NOT_EXISTS', 4804);

//信用状况监测管理舆情信息错误规范
define('MONITOR_OPINION_NAME_FORMAT_INCORRECT', 4901);
define('MONITOR_OPINION_KEYWORD_FORMAT_INCORRECT', 4902);
define('MONITOR_OPINION_CATEGORY_FORMAT_INCORRECT', 4903);
define('MONITOR_OPINION_SOURCE_FORMAT_INCORRECT', 4904);
define('MONITOR_OPINION_PUB_DATE_FORMAT_INCORRECT', 4905);
define('MONITOR_OPINION_CONTENT_FORMAT_INCORRECT', 4906);

//信用状况监测管理重点关注错误规范
define('MONITOR_FOCUS_MONITOR_IDENTIFY_FORMAT_INCORRECT', 5001);
define('MONITOR_FOCUS_MONITOR_SUBJECT_CATEGORY_FORMAT_INCORRECT', 5002);
define('MONITOR_FOCUS_MONITOR_PENALTY_THRESHOLD_FORMAT_INCORRECT', 5003);
define('MONITOR_FOCUS_MONITOR_DISHONESTY_THRESHOLD_FORMAT_INCORRECT', 5004);
define('MONITOR_FOCUS_MONITOR_IDENTIFY_EXISTS', 5005);

//错敏词库管理错误规范
define('SENSITIVE_WORD_NAME_FORMAT_INCORRECT', 5101);
define('SENSITIVE_WORD_SOURCE_FORMAT_INCORRECT', 5102);
define('SENSITIVE_WORD_REMARK_FORMAT_INCORRECT', 5103);
define('SENSITIVE_WORD_NAME_EXISTS', 5104);
